name: Backend Docker Build & Deploy

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
      - 'backend/Dockerfile'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: financial-app-backend

    steps:
    - uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and Push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./backend
        push: true
        build-args: |
          NODE_VERSION=22
        tags: |
          ${{ secrets.REGISTRY_USERNAME }}/${{ env.IMAGE_NAME }}:latest
          ${{ secrets.REGISTRY_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
        cache-from: type=registry,ref=${{ secrets.REGISTRY_USERNAME }}/${{ env.IMAGE_NAME }}:buildcache
        cache-to: type=registry,ref=${{ secrets.REGISTRY_USERNAME }}/${{ env.IMAGE_NAME }}:buildcache,mode=max

    - name: Trigger Portainer Webhook
      run: |
        curl -X POST ${{ secrets.PORTAINER_WEBHOOK_BACKEND }} \
          -H "Content-Type: application/json" \
          --fail
